### ISSUE TITLE
Add logs section to the docker-compose file

### ISSUE THREAD

**Issue by egorsmkv** [egorsmkv/laravel-boilerplate-dev#23]
```
version: '3.7'
services:
  app:
    image: ...
    logging:
      options:
        max-size: "10m"
        max-file: "3"
```
